name: Trigger another job
on: ["push", "workflow_dispatch"]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: triggering GA Repo
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACTIONS_KEY }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'Shankarsharm',
            repo: 'GA_Actions',
            workflow_id: 'swc.yml',
            ref: 'master'
          })
